INSERT INTO TBL_PRODUCT(PRICE, DESCRIPTION) VALUES ( 20, 'Apple');
INSERT INTO TBL_PRODUCT(PRICE, DESCRIPTION) VALUES ( 25, 'Samsung');
INSERT INTO TBL_PRODUCT(PRICE, DESCRIPTION) VALUES ( 12, 'Xiaomi');
INSERT INTO TBL_PRODUCT(PRICE, DESCRIPTION) VALUES ( 32, 'Telefônica');
